### ISSUE TITLE
Active: To-do

### ISSUE THREAD

**Issue by tgoodbody** [tgoodbody/sgsR#11]
- [x] Add allocation method to allow for user defined weights
- [x] Allow `buff_inner` to be NULL to permit users to not specify a minimum distance samples should be from roads
- [x] Add `testthat::use_test()` for all functions

**Comment by tgoodbody** [comment]
Added allocation method `"manual"` and `weights` parameter in #12

**Comment by tgoodbody** [comment]
`buff_inner` can now remain the default `NULL` value allowing users to not specify minimum distance samples should be from roads. [commit](https://github.com/tgoodbody/sgsR/commit/2f4e720635dcf622d69d795e892b2ef8a02cfb24)

**Comment by tgoodbody** [comment]
Unit tests added
